### ISSUE TITLE
LIKE 关键字怎么使用？

### ISSUE THREAD

**Issue by includeleec** [nnnewb/leancloud-better-storage-python#1]
包含查询类似于 SQL 的 LIKE '%keyword%' 条件，比如查询标题包含「李总」的 Todo：

import leancloud

Todo = leancloud.Object.extend('Todo')
query = Todo.query

query.contains('title', '李总')

请问这种方法，怎么使用？

**Comment by nnnewb** [comment]
可以用query.filter(Model.title.contains("李总"))这种形式，暂时只支持contains这一种模式匹配字符串的条件。

**Comment by nnnewb** [comment]
有需要可以用query.build_query()得到leancloud sdk提供的Query对象
