### ISSUE TITLE
考虑重写部分实现

### ISSUE THREAD

**Issue by nnnewb** [nnnewb/leancloud-better-storage-python#3]
目前两个想法。

一个是个人感觉蛮有意思但是不大合适的，利用Python3的type annotation对字段做类型注解，把Field类之类的细节隐藏掉。

实现后的声明代码大概是这样。

```python
class A(Model):
    id: (int, unique)
    name: chars(8)
```

第二个想法是利用Descriptor替换掉现在的Model里那堆实现。实现后对可维护性可扩展性应该有极大的提升。

大概方案是把Model里的__getattr__和__setattr__这些东西丢掉，Field重载__get__和__set__，考虑不同类型的字段只需要在对应的__get__和__set__里做处理就好了。

**Comment by Leechael** [comment]
我的初衷是尽可能和 SQLAlchemy 兼容，并且能无缝地和 Marshmallow 配合，最后 Batch 功能要大规模用上（我有大量数据操作的需求，官方的 SDK 没有做好这个）。因此设计方案或者可以考虑用一些伪代码来表示一下？

**Comment by Leechael** [comment]
为什么不用 Type Annotation，我觉得唯一的理由就是扩展吧。例如现在 DatetimeField 和 DateField，可能可以集成进去，但 ArrowField 就不一定了。可能还有一些其他 Field 类型，例如 CurrencyField，GeoField，等等，参考 sqlalchemy-utils，只靠 type annotation 可能表达能力不足应对更多的场景。

**Comment by nnnewb** [comment]
> 我的初衷是尽可能和 SQLAlchemy 兼容，并且能无缝地和 Marshmallow 配合，最后 Batch 功能要大规模用上（我有大量数据操作的需求，官方的 SDK 没有做好这个）。因此设计方案或者可以考虑用一些伪代码来表示一下？

关于 Type Annotation 的想法并没有落实下去的想法，也许会自己另外搞个玩具出来。

而 descriptor 改写实现这一条正在着手中，会尽快拿个样例出来。最近几天事情都堆在一起比较忙，我尽量不鸽吧......

**Comment by nnnewb** [comment]
descriptor 改写逻辑比预想的简单得多，这是[改写的那次提交](https://github.com/nnnewb/leancloud-better-storage-python/commit/2833a0b12203d32fef03cadfb4e62afe572fa79a)。
